version: "3.9"
services:
  frontend:
    image: woghks778803/docker-frontend
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./frontend
    volumes: 
      - /var/www/frontend/node_modules
      - ./frontend:/var/www/frontend
    stdin_open: true

  backend:
    container_name: app_backend
    image: woghks778803/docker-backend
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./backend
    volumes: 
      - /var/www/backend/node_modules
      - ./backend:/var/www/backend
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
    
  nginx:
    restart: always
    image: woghks778803/docker-nginx
    # build:
    #   dockerfile: Dockerfile
    #   context: ./nginx
    ports:
      - "80:80"

  # mysql:
  #   restart: unless-stopped
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./mysql
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: myapp
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 50M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 20M

