FROM node:alpine

WORKDIR /var/www/html

COPY package.json ./

RUN npm install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
# RUN chown -R node:node /var/www/html/node_modules

COPY ./ ./

ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "start"]

# docker build -t jpro/docker-react-app -f Dockerfile.dev ./

# Windows
# docker run -d -p 3000:3000 -v /var/www/html/node_modules -v %cd%:/var/www/html jpro/docker-react-app
# Mac, Linux, Unix
# docker run -d -p 3000:3000 -v /var/www/html/node_modules -v $(pwd):/var/www/html jpro/docker-react-app
# docker buildkit을 사용하지 않겠다고 설정하는 방법으로 해결할 수 있습니다. bulidkit은 docker bulid . 명령어를 사용할 수 있도록 하는 환경설정 중 하나입니다.
# export DOCKER_BUILDKIT=0 
# export COMPOSE_DOCKER_CLI_BUILD=0