version: "1"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - /var/www/frontend/node_modules
      - ./frontend:/var/www/frontend
    stdin_open: true
  backend:
    container_name: app_backend
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes: 
      - /var/www/backend/node_modules
      - ./backend:/var/www/backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: jpro 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306    
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
  # mysql:
  #   restart: unless-stopped
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./mysql
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: myapp

